import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Vendored: regenerated by `shadcn add`, and by drizzle-kit. Linting them
    // only produces churn we would have to re-apply on every regeneration.
    "src/components/ui/**",
    "src/hooks/**",
    "drizzle/**",
  ]),
]);

export default eslintConfig;
